from save_review import save
save(1163,{
2:'复合武器是帝国和混沌军队使用的一类枪械，本质上是把两种武器合为一体。英文通常以 Combi- 加武器名，或 Bolter- 加另一种武器名来命名。有时，近战武器与远程武器的组合也使用 Combi- 这一前缀。',
5:'早在荷鲁斯叛乱之前，星际战士就已使用复合爆矢枪。它实际上是将两把爆矢枪并装而成。帝国后来转而生产更先进的后继型号——风暴爆矢枪，不再制造复合爆矢枪，但仍将少量存品作为古老遗物保存。混沌星际战士也普遍使用这种武器。',
25:'炼狱重型爆矢枪是死亡守望使用的重型复合喷火武器，将重型爆矢枪与重型喷火器合为一体，并以磁性夹具固定悬浮减重盘，减轻持用负担。',
36:'Raven Guard Heresy-era Tigris Pattern Combi-Melta 暗鸦守卫在荷鲁斯叛乱时期使用的泰格鲁斯型复合热熔枪',
40:'Alpha Legion Heresy-era Phobos Pattern Combi-Melta 阿尔法军团在荷鲁斯叛乱时期使用的火卫一型复合热熔枪',
51:'Horus Heresy-era Thousand Son with an Umbra-Ferrox pattern Combi-Plasma 荷鲁斯叛乱时期，装备影铁型复合等离子枪的千子战士',
54:'星际战士使用的复合武器，由重力枪与爆矢枪组合而成。',
56:'Ultramarine Sternguard Veteran with a master-crafted Combi-Grav Gun 装备精工复合重力枪的极限战士肃卫老兵',
69:'涅克罗蒙达埃舍尔家族使用的武器，将爆矢枪与针刺枪合为一体。',
81:'Executioner Pistol a Combi-Needle Pistol used by the Eversor Temple of the Officio Assassinorum 刽子手手枪，刺客庭艾弗森神庙使用的复合针刺手枪',
83:'ganger of House Escher with an Escher pattern Combi-Needler 装备埃舍尔型复合针刺枪的埃舍尔家族帮派成员',
84:'Condemnor Boltgun (Combi-Stake Crossbow) 宣判者爆矢枪（复合桩弩）',
86:'这种爆矢枪在侧面装有一具桩弩，适合对付灵能者，使用者几乎全是异端审判庭成员和战斗修女。',
88:'宣判者爆矢枪名副其实，令银河各处的灵能者闻之胆寒。爆矢枪本身就已足够致命，而安装在枪身上的弩还能射出经过祝福的“净化者”桩形弩矢，击倒恶魔与巫师。这类神圣武器极其稀少，却是对抗亚空间力量使用者的强大兵器。',
93:'少数星际战士使用的极罕见武器。这些黑暗科技时代的遗物，将爆矢枪与一支辅助分解枪合为一体。',
96:'Adrastus bolt caliver 阿德拉斯托斯速射爆矢枪',
98:'阿德拉斯托斯速射爆矢枪结合了较后期的帝国爆矢武器设计与黑暗科技时代的“阿德拉斯泰特”分解光束技术；后者在大远征中被禁止普遍配发。这种威力强大的肩射武器，是禁军军团使用的便携式重武器。它既能在远距离连射爆炸弹丸，威力堪比阿斯塔特军团使用的重型爆矢枪，也能在较近距离发射分解光束，从分子层面撕裂目标，使受害者在轰鸣的能量闪光中化为乌有。',
100:'Sagittarum Guard Custodes with a Adrastus bolt caliver 装备阿德拉斯托斯速射爆矢枪的禁军射手',
103:'等离子爆破枪实际上是将两支等离子枪合为一体。它的射程略短，但两个发射腔会同时放电，使杀伤力加倍。这类武器比现代等离子枪更可靠，因为帝国初创时对等离子技术的掌握远比后世深入。它们诞生于大远征时代，在第41个千年的战场上已几乎绝迹，只有少数作为遗物留存在阿斯塔特的军械库中。第一次泰伦战争期间，极限战士第一连长索尔·英维克图斯就曾在战斗中使用等离子爆破枪。',
108:'涅克罗蒙达凡·萨尔家族使用的武器，由热熔手枪与激光手枪组合而成。',
110:'Magna-Needle Mk.X Pattern Pistol 巨型针刺 Mk.X 型手枪',
113:'涅克罗蒙达凡·萨尔家族使用的武器，由等离子手枪与激光手枪组合而成。',
115:'Ultra-Needle Mk.IX Pattern Pistol 极限针刺 Mk.IX 型手枪',
116:'Stub Gun-Plasma Combi-Pistol 短管枪—等离子复合手枪',
118:'在等离子手枪上附装短管枪而成的复合武器，由涅克罗蒙达的歌利亚家族使用。',
120:'Stub Gun-Plasma Combi-Pistol 短管枪—等离子复合手枪',
125:"Alexis Polux's combi-fist. Integrated with a Combi-Melta 亚历克西斯·泼鲁克斯的复合拳套，内置复合热熔枪",127:'Auto Boltstorm Gauntlets, used by Aggressors. Integrated with boltguns 侵略者使用的自动爆矢风暴臂铠，内置爆矢枪',129:'Flame Gauntlet, used by Aggressors. Integrated with a flamer 侵略者使用的烈焰臂铠，内置喷火器',
130:'Autoch-Pattern Combi-Bolter 奥托克型复合爆矢枪',134:'Autoch-Pattern Combi-Bolter 奥托克型复合爆矢枪',136:'RAM Shield with built-in Autoch-Pattern Combi-Bolter 内置奥托克型复合爆矢枪的 RAM 盾',
139:'仲裁者——荷鲁斯叛乱期间，罗保特·基里曼作为随身副武器使用的复合爆矢枪。',
147:"Lion's Roar, a relic Combi-Plasma that uses a Plasma Blaster instead of a Plasma Gun 狮之咆哮，一件以等离子爆破枪替代常规等离子枪的复合等离子枪遗物",149:'统御之手——罗保特·基里曼使用的复合拳套。',151:'Hand of Dominion Integrated with a boltgun 统御之手，内置爆矢枪',155:'Gauntlets of Ultramar. Integrated with a boltgun 奥特拉玛之拳，内置爆矢枪',157:'荷鲁斯之爪——内置风暴爆矢枪的闪电爪，由荷鲁斯·卢佩卡尔和以泽凯尔·阿巴顿先后使用。',159:'黑矛——内置强力激光武器的动力长矛，由阿斯忒里昂·摩洛克使用。',161:'阿卡诺斯之杖——内置辅助榴弹发射器的教士权杖，由伊万努斯·恩科米使用。',163:'门扉制造者——来自侵略者战团的复合热熔枪，目前由杰里科守望要塞使用。'},
{36:'Heresy-era 指叛乱时期，原译“叛乱前”误将时代前移；40、51段同改。Tigris/Tigrus 英文保留异拼，中文按同类武器型号沿泰格鲁斯。',56:'Sternguard Veteran 为肃卫老兵，不是老兵军士；master-crafted 译精工。',86:'Ordo Hereticus 是异端审判庭，原译圣锤修会误指另一分支。',98:'prohibited from general issue 限定阿德拉斯泰特分解武器不得普遍配发，不是整个复合武器被禁用；shoulder arm 是肩射武器，不是臂膀。',130:'Autoch 为专有型号名，不能按 auto 直接译“自动”；暂音译奥托克。'},
[('Combi-weapon','复合武器'),('Combi-Bolter','复合爆矢枪'),('Phobos-pattern Combi-Bolter','火卫一型复合爆矢枪'),('Tigrus Pattern Combi-Bolter','泰格鲁斯型复合爆矢枪'),('Umbra-Ferrox','影铁'),('Combi-Flamer','复合喷火器'),('Infernus Heavy Bolter','炼狱重型爆矢枪'),('Combi-Melta','复合热熔枪'),('Combi-Plasma Gun','复合等离子枪'),('Combi-Grav Gun','复合重力枪'),('Combi-Volkite','复合爆燃枪'),('Combi-Grenade Launcher','复合榴弹枪'),('Combi-Needler','复合针刺枪'),('Needlespine Blaster','针脊冲击枪'),('Combi-Needle Pistol','复合针刺手枪'),('Executioner Pistol','刽子手手枪'),('Condemnor Boltgun','宣判者爆矢枪'),('Purgatus','净化者'),('Disintegration Combi-gun','复合分解枪'),('Adrastus bolt caliver','阿德拉斯托斯速射爆矢枪'),('Adrastite','阿德拉斯泰特'),('Plasma Blaster','等离子爆破枪'),('Magna-Needle','巨型针刺'),('Ultra-Needle','极限针刺'),('Stub Gun-Plasma Combi-Pistol','短管枪—等离子复合手枪'),('Combi-Fist','复合拳套'),('Autoch-Pattern Combi-Bolter','奥托克型复合爆矢枪'),('Arbitrator (Guilliman weapon)','仲裁者'),("Lion's Wrath",'雄狮之怒'),("Lion's Roar",'狮之咆哮'),('Hand of Dominion','统御之手'),('Talon of Horus','荷鲁斯之爪'),('Black Spear','黑矛'),('Crozius Arkanos','阿卡诺斯之杖'),('Gate Maker','门扉制造者')])
