from save_review import save
from pathlib import Path
import json,re
C=next(a for a in json.loads((Path(__file__).parents[2]/'全书分段底稿.json').read_text()) if a['number']==1162)
ed={1:'Willingly you picked me up. Your first mistake. Willingly you drew me. Your second mistake. I do not allow my servants to make three mistakes, foolish mortal... - A Daemon Weapon 你自愿拿起了我，这是你的第一个错误。你自愿将我出鞘，这是你的第二个错误。我不允许仆人犯下第三个错误，愚蠢的凡人……——一把恶魔武器',3:'恶魔武器是混沌诸神赐予的礼物，供混沌冠军和恶魔使用。每件武器中都束缚着一个恶魔的灵魂，永远囚禁于此；有时，恶魔甚至是自愿接受束缚的。',8:'只有混沌诸神最强大的仆从才会获赐恶魔武器，包括大魔、恶魔王子，以及尚为凡人之身的混沌冠军。每件武器都独一无二，能赋予持有者强大的力量。不过，武器中受缚的恶魔有时也会压倒企图驾驭它的主人的意志。',12:'没有恶魔喜欢受人束缚；若被困在盾牌这类并非用于杀戮的器物中，它们尤其愤懑。长期得不到杀戮与鲜血的滋养，足以使恶魔发疯。',16:'恐虐之斧——巨大而华丽的战斧，其中灌注着恐虐永不餍足的嗜血欲望。它们通常由嗜血狂魔使用，有时也会赐给其他配得上这份赏赐的恐虐冠军。',18:'狂战士长刀——持有者必须不断与这件武器抗争，才能维持对它的控制。刀刃中束缚着一名放血者的精魄，长期囚禁已使它彻底陷入疯狂。',21:'嗜血者——通常呈战斧形态，其中束缚着一名狂怒的嗜血狂魔的精魄。',28:'火焰风暴刃——巨大而炽烈的火焰刀刃，有些嗜血狂魔会使用这类武器。',34:'地狱之刃——放血者使用的武器。',36:'饥血者卡托斯——恐虐亲自使用的利刃。',59:'收割者——浸染了从纳垢王座渗出的污秽的武器。',61:'传染法杖——用来将纳垢的疾病从亚空间带入物质界的容器。战斗中，这些疾病会被释放出来，吞噬敌军。',65:'瘟疫使者——其中藏有恶魔病菌，毒性之烈足以杀死最顽强的敌人。',73:'欲望之针——将使用者带有麻醉作用的体液注入敌人体内。',85:'混乱之杖——千子最古老的武器之一，能够使敌人暂时陷入恍惚。',87:'死亡尖啸者——发射魔法轰击。',89:'Everstave 永恒之杖',101:'次元之刃——能够消解灵能力量。',102:'Unaligned Daemon Weapons 无特定神祇归属的恶魔武器',106:'诅咒权杖——黑暗使徒使用的武器。',111:'畏惧之斧——具有吸血特性的利刃，对其他恶魔尤为有效。',114:'以太长枪——发射亚空间能量束。',119:'凯枪——以持有者的仇恨为动力的远程武器。',127:'安特维尔之刃——克罗堡主使用的剑。',132:'暗影之刃——比拉克尔的恶魔之剑。',140:'德拉科尼恩——掠夺者阿巴顿使用的恶魔之剑。',142:'破炉者——钢铁勇士的恶魔原体佩图拉博使用的恶魔雷霆锤。',144:'狱矛——夺星者哈尔肯使用的武器。',146:'卡纳加尔——审判官奇科索斯使用的恶魔之剑，其中束缚着“死亡者卡纳加尔”的精魄。',148:'折磨之鞭——一条活生生的长鞭，通体布满凶恶的尖刺，触手温热。它以受害者的痛苦和恐惧为食，还会放大这些情绪，使周围的人陷入惊恐。',151:'尖啸连枷——色孽的恶魔连枷，被遗物守护者夺取后，重新命名为“阿特库斯之灾”。'}
notes={18:'fight with 此处是持有者与武器意志抗争，原译“与其一起战斗”颠倒关系。',61:'vessels for diseases 是装载疾病的容器，原译“用于治疗”与原义相反。',102:'unaligned 指未归属于某一特定混沌神，不等于所有使用者都信奉同一种“混沌无分”教义。',146:'the Deathly 暂译死亡者；原“思死者”没有明确英文依据，完整称号待核。',151:'Taken by 指被夺取，不只是携带。'}
terms=[]
for b in C['blocks']:
 if b['language']=='zh' and b['id'] not in {'A1162-B0001'}:
  t=ed.get(int(b['id'][-4:]),b['text']);m=re.match(r'([A-Za-z][^\u3400-\u9fff]*?)\s+([\u3400-\u9fff].*)$',t)
  if m and len(t)<100 and not m[1].startswith(('Overview','Daemon Weapons','Unaligned','Notable')):terms.append((m[1],m[2]))
terms += [('Daemon Weapon','恶魔武器'),('Axe of Khorne','恐虐之斧'),('Berzerker Glaive','狂战士长刀'),('Bloodfeeder','嗜血者'),('Firestorm Blades','火焰风暴刃'),('Hellblade','地狱之刃'),('Khartoth the Bloodhunger','饥血者卡托斯'),("Schlack'ta","斯拉克'塔"),("An'garrach","安'加拉赫"),('Pandemic Staff','传染法杖'),('Plaguebringer','瘟疫使者'),('Blissgiver','赐福者'),('Needle of Desire','欲望之针'),('Bedlam Staff','混乱之杖'),('Deathscreamer','死亡尖啸者'),("Krz'at'tchal","克'扎特'查尔"),('Warp Blade','次元之刃'),("Ul'o'cca, the Black Axe","黑斧乌尔'欧'卡"),('Accursed Crozius','诅咒权杖'),('Dark Blade','黑暗之刃'),('Ether Lance','以太长枪'),('Kai Gun','凯枪'),('Vilemaw','卑鄙之喉'),('Black Blade','黑刃'),('Blade of Antwyr','安特维尔之刃'),('Blade of Magnus','马格努斯之刃'),('Blade of Shadows','暗影之刃'),("Borhg'ash","博尔格'阿什"),('Carnage and Slaughter','屠杀与杀戮'),('Deii’Sh’thuhl',"黛伊'斯'朔尔"),('Helspear','狱矛'),('Kharnagar','卡纳加尔'),('Kharnagar the Deathly','死亡者卡纳加尔'),('Lash of Torment','折磨之鞭'),('Artekus Scourge','阿特库斯之灾'),('Silver Blade of the Laer','莱尔银刃'),('Souleater Sword','食魂者之剑')]
save(1162,ed,notes,terms)
