import csv,pathlib,json
P=pathlib.Path(__file__).parent
fields=['英文标准词','采用中文','译名状态','依据','定位','编辑说明']
pairs={
'Ordo Xenos':'异形审判庭','Ordo Hereticus':'异端审判庭','Ordo Malleus':'恶魔审判庭','Decree Passive':'禁武法令','Witch Hunters':'猎巫者','Thorians':'托尔派','Promeans':'普罗密斯派','Horusians':'荷鲁斯派','Divine Avatar':'神圣化身','Incunabla':'因库纳布拉','Tyrama Secundus':'泰拉玛二号','Inquisitorial Representative':'审判庭代表','Inquisitor Lord':'领主审判官','Grandmaster':'大导师','Master':'导师','Novitiate':'见习者','Neophyte':'新进者','Approbator':'考核者','Legate Investigator':'调查使节','Agent of Reliquary 26':'第26圣物库特工','Metallican Gunslinger':'梅塔利卡枪手','Malfian Bloodsworn':'马尔菲安血誓者','Drill Abbot':'训导院长','Verminspeaker':'虫鼠语者','Techsorcist':'技术驱魔师','Pyroclast':'焚火者','Ecclesiarch':'教宗','Cardinal':'红衣主教','Confessor':'告解者','Preacher':'传道士','Missionary':'传教士','Cenobite':'共修修士','Militant-Apostolic':'战争使徒','Creed Temporal':'世俗教务部','Synod Ministra':'辅圣会','Euphrati Keeler':'尤弗拉蒂·琪乐','The Beheading':'斩首事件','Temple of the Saviour Emperor':'救世帝皇圣堂','Confederation of Light':'光明同盟','Lectitio Divinitatus':'帝皇圣言录／圣言诵读','Missionaria Galaxia':'银河传教团','Missionarus Galaxia':'银河传教团','Ministorum Galaxia':'银河传教团','Confessor-Militant':'军务告解者','Missionary Vessel':'传教船','Mission':'教团／传教机构','Cults of the Voice':'圣声教派','Voice of the Emperor':'帝皇之声','Rawketh':'罗凯斯','Marduk':'马尔杜克','Acts of Faith':'信仰伟业','Abbess of the Adepta Sororitas':'修女会总院长','Prioress':'院长','Orders Militant':'战斗修会','Non-Militant Orders':'非战斗修会','Order of Our Martyred Lady':'殉教圣女修会','Orders Hospitaller':'医疗修会','Orders Dialogus':'书记修会','Order of the Sacred Rose':'神圣玫瑰修会','Order of the White Rose':'白色玫瑰修会','Order of the Wounded Heart':'受伤之心修会','Order of the Fiery Tear':'炽热之泪修会','Order of the Valorous Heart':'勇毅之心修会','Order of the Bloody Rose':'鲜血玫瑰修会','Order of the Glowing Chalice':'炽光圣杯修会','Illuminata':'伊卢米娜塔','Alexis de Chatelaine':'亚历克西斯·德·沙特莱纳','Veridyan':'维里迪安','Writ Illuminat':'辉光敕书','Anais':'安娜伊斯','Saint Lucia':'圣露西亚',
}
official={'Morvenn Vahl':'莫雯·瓦尔','Junith Eruita':'茱妮丝·伊瑞塔','Saint Celestine':'圣塞莱斯汀','Aestred Thurga':'阿斯垂德·瑟加','Agathae Dolan':'阿加瑟·多兰','Ministorum Priest':'教廷牧师','Hospitaller':'医疗修女','Dialogus':'书记修女','Arco-flagellants':'鞭挞苦修者','Canoness':'大修女','Palatine':'宫廷官','Imagifier':'持像者','Dominion Squad':'御天使小队','Retributor Squad':'仇天使小队','Zephyrim Squad':'风天使小队','Seraphim Squad':'炽天使小队','Paragon Warsuits':'楷模机甲','Mortifiers':'悔罪者机甲','Penitent Engines':'忏悔者机甲','Exorcist':'驱魔人导弹车','Castigator':'惩戒者坦克','Immolator':'献祭者装甲车','Dogmata':'教条官','Celestian Sacresants':'洁天使圣徒','Repentia Squad':'忏悔修女小队'}
notes={'Master':'只限审判庭地区组织职衔，不与 Sensei 合并。','Mission':'修女会编制称教团；教会学校医院等慈善传教设施称传教机构，按语境区分。','Lectitio Divinitatus':'书名采用《帝皇圣言录》，相应信仰运动称圣言诵读。','Orders Hospitaller':'组织名由官方单位称谓衍生，未找到组织名直接官方中文，不标官方。','Orders Dialogus':'组织名由官方单位称谓衍生；Dialogous 是文中异拼。','Ministorum Priest':'仅完整职位名称；不将泛称 Priest 或其他组织的 Chaplain 一律替换。','Exorcist':'仅修女会载具；同名驱魔者职务或战团名称须按语境另译。','Castigator':'仅修女会载具；同名人员/武器按语境区分。','Pyroclast':'105 篇人员类型；不得套普通名词火山岩，也不据此替换其他同名装备。','Euphrati Keeler':'Euphrati 是人名，不沿用河名幼发拉底；暂定音译。','Approbator':'候选审判官的学徒称谓，暂定。','Decree Passive':'原稿兼有被动法令、驯服教令；取反映禁止教会武装男性的暂译。','Hospitaller':'官方单名单位；Sister Hospitaller 可据语境沿用。'}
rows=[]
for en,zh in pairs.items():
 rows.append([en,zh,'暂定','原书英文语境','第101—123篇',notes.get(en,'本批统一译名，未声称官方认证。')])
for en,zh in official.items():
 rows.append([en,zh,'官方已核对','GW-09；GW-10','GW-09 简体中文 PDF 第2页；GW-10 英文 PDF 第2页',notes.get(en,'官方军务部战地手册同名单位中英对照；不依据点数顺序硬配。')])
with (P/'terms.tsv').open('w') as f:
 w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(fields);w.writerows(rows)
t={'101':'异形审判庭 Ordo Xenos','102':'异端审判庭 Ordo Hereticus','106':'国教会 Ecclesiarchy','107':'帝皇信仰 Imperial Cult','110':'世俗教务部 Creed Temporal','112':'银河传教团 Missionaria Galaxia','117':'教廷牧师 Ministorum Priest'}
(P/'titles.json').write_text(json.dumps(t,ensure_ascii=False,indent=2)+'\n')
