from save_review import save
save(1284,{2:'攻城热熔阵列是星际战士乳齿象载具在大远征和荷鲁斯之乱期间使用的热熔武器。这种巨型武器能轻易摧毁防御工事，也能迅速消灭装甲载具。'},terms=[('Siege Melta Array','攻城热熔阵列')])
save(1285,{2:'旋风热熔光矛是帝国的重型热熔武器，在大远征和荷鲁斯之乱时期专为利维坦攻城无畏机甲研制，能将敌方装甲熔成残渣。'},terms=[('Cyclonic Melta Lance','旋风热熔光矛')])
save(1286,{2:'重力武器是可追溯至黑暗科技时代的古老武器，其原理鲜为人知。',6:'这一名称泛指一类重力投射装置。它们技术极其复杂，即使在大远征时代，留存下来的数量也已很少。不过，在星舰内部或零重力环境中，它们极有价值。重力枪调至最高功率时，足以隔着护甲震碎骨骼、撕裂脏器，但主要用途仍是阻滞敌人和破坏机械。',11:'Graviton Mace 重力战槌',12:'Graviton Crusher 重力粉碎器',17:'Graviton Cannon - Heavy vehicle-based version 重力炮——重型车载版本',23:'Grav Flux Bombard 重力通量轰击炮',25:'Graviton Charge Cannon 重力充能炮',26:'Graviton Onager 重力投石机'},notes={6:'few remained指留存的武器很少，不是“很少有人留下来”。',11:'Mace为打击兵器，不是象征权力的权杖。'},terms=[('Graviton Weapon','重力武器'),('Graviton Hammer','重力锤'),('Graviton Mace','重力战槌'),('Graviton Crusher','重力粉碎器'),('Graviton Maul','重力槌'),('Graviton Gun','重力枪'),('Graviton Cannon','重力炮'),('Graviton Imploder','重力内爆器'),('Combi-Grav','复合重力枪'),('Graviton Pulsar','重力脉冲枪'),('Graviton Singularity Cannon','重力奇点炮'),('Grav Flux Bombard','重力通量轰击炮'),('Graviton Ram','重力攻城锤'),('Graviton Charge Cannon','重力充能炮'),('Graviton Onager','重力投石机'),('Krius Grav Imploder','克里乌斯重力内爆器'),('Graviton Destructor','重力破坏者'),('Graviton Ruinator','重力毁灭者'),('Giga-Graviton Cannon','千兆重力炮'),('Graviton Rifle','重力步枪'),('Graviton Blast Cannon','重力冲击炮')])
save(1287,{2:'重力手枪在英文中称为 Graviton Pistol 或 Grav-Pistol，是帝国的手持式重力武器。'},terms=[('Graviton Pistol','重力手枪'),('Grav-Pistol','重力手枪')])
save(1288,{9:'它是一种中型武器，利用与兰德速攻艇等反重力载具相同的重力反应原理。每一把都是黑暗科技时代留下的稀有遗物，如今由机械修会严加珍藏，极少获准离开军械库。不过，一些星际战士战团仍有少量装备。',11:'Heresy-era Autotellurian-Pattern Graviton gun 荷鲁斯之乱时期的自动实相型重力枪',13:'重力枪最初用于低重力环境中的民用作业，以增加物体的相对重量。它发射的粒子流会改变目标区域的局部引力场，按设定使目标显著变重或变轻。重力波影响局部气压、使空气振动时，还会发出低沉轰鸣。这种效果通常不致命，可用于制服需要活捉的敌人；但最高功率仍足以隔着护甲撕裂脏器、折断骨骼。不同生物受到的影响不尽相同，庞大生物可能被自身骤增的重量压死，而多数目标则会行动迟缓或完全无法移动。重力枪不仅适合星舰内部和零重力作战，也可用于拆除和攻城。碉堡或防御工事等巨型目标尤为脆弱，其庞大质量反而会成为致命弱点，使建筑自行坍塌。',19:'一种便于进行多种改装的重力枪，在涅克罗蒙达的帮派成员和雇佣枪手中很受欢迎。'},notes={9:'Land Speeder是兰德速攻艇，原译兰德掠袭者混淆了两类载具；grav-vehicles是反重力载具，不是轻型载具。'},terms=[('Graviton Gun','重力枪'),('Autotellurian Pattern','自动实相型'),('Hystrar Mk.XII Pattern','海斯特拉 Mk.XII 型'),('Wrath Gravgun','暴怒重力枪')])
save(1289,{2:'Heavy Grav-Cannon on the Kataphron Destroyer 铁甲破坏者上的重型重力炮',4:'重力炮是一种大型重力投射武器，威力足以隔着护甲撕裂脏器、折断骨骼，但主要用途是在避免二次爆炸的情况下破坏敌方机械。细剑载具和百夫长装甲都曾装备重力炮；机械修会还使用重型版本，单次射击便能将泯灭者撕成两截。'},terms=[('Graviton Cannon','重力炮'),('Heavy Grav-Cannon','重型重力炮')])
save(1290,{2:'重力充能炮是帝国在大远征和荷鲁斯之乱期间，安装于曲射手臼炮载具上的重力武器。',4:'Arquitor Bombard with Graviton Charge Cannon 装备重力充能炮的曲射手臼炮载具',6:'这种独特的重力技术武器会发射充能弹筒，命中后释放极强重力场，将步兵牢牢压在地面，并碾碎电路和电子设备。它不仅能消灭敌人，也很擅长阻滞敌军推进。'},terms=[('Graviton Charge Cannon','重力充能炮')],title='重力充能炮 Graviton Charge Cannon')
save(1291,{2:'重力通量轰击炮是一种专为利维坦无畏机甲研制的重型重力武器，用于近距离攻城。'},notes={2:'Flux沿技术术语译通量，原题熔解误义，统一正文与标题。'},terms=[('Grav Flux Bombard','重力通量轰击炮')],title='重力通量轰击炮 Grav Flux Bombard')
