from save_review import save
save(1271,{2:'重型火焰喷射器是体积和重量都明显增加的火焰喷射器。',4:'Imperial Heavy Flamer 帝国重型火焰喷射器',7:'它喷出的火焰规模更大，能够吞没更多目标。除星际战士、战斗修女和混沌星际战士等部队外，很少有军队以单兵方式携行使用它，但有时会将其装在载具上。卡塔昌丛林斗士也是例外：丛林战让火焰武器格外重要，因此他们会携带这种重型装备。它同时也是星际战士终结者的标准特殊武器之一。',13:'费斯托斯型——荷鲁斯之乱期间使用。',15:'Phaestos-Pattern Heavy Flamer 费斯托斯型重型火焰喷射器',17:'普罗透斯型——荷鲁斯之乱期间使用。',19:'Proteus-Pattern Heavy Flamer 普罗透斯型重型火焰喷射器'},terms=[('Heavy Flamer','重型火焰喷射器')],title='重型火焰喷射器 Heavy Flamer')
save(1272,{2:'燃烧炮是不败者战术机甲使用的火焰武器，能够喷出炽烈焰流，将大片敌人烧成燃烧的尸体。'},terms=[('Incendium Cannon','燃烧炮')])
save(1273,{2:'炼狱炮是一种巨型火焰武器，安装于帝国泰坦及其他超重型载具。',4:'它由数根联动炮管组成，喷射极易燃烧的化学物，形成巨大的火浪。通常所用燃料是钷素，其组分分别储存，再独立泵入炮管后方的混合室，形成化学凝胶。凝胶经压缩后化为燃烧喷流射出，黏附在接触到的表面上。这股如太阳般炽烈的火焰能够熔化岩石和混凝土，使建筑自行坍塌，甚至将动力装甲步兵连人带甲熔毁。突如其来的高温还会触发地雷引信，因此也能有效清理雷区。',6:'Inferno Guns from various Imperial vehicles: 1-Warhound Scout Titan, 2-Malcador Infernus 不同帝国载具上的炼狱炮：1—战犬级侦察泰坦；2—炼狱马卡多',8:'炼狱炮可安装于战犬级侦察泰坦的臂部，以及掠夺者级和战将级战斗泰坦的背甲武器座。部分帝皇级泰坦的背甲上也有此类武器。帝国卫队的炼狱马卡多超重型坦克同样以炼狱炮为主武器，但必须拖带一辆独立的钷素燃料拖车。'},terms=[('Inferno Gun','炼狱炮')])
save(1274,{2:'火焰风暴炮是一种大型帝国火焰喷射器，威力甚至超过多种星际战士载具使用的重型火焰喷射器。每门炮都能向敌群倾泻滚滚燃烧的钷素。这种武器可安装在救赎者型兰德掠袭者的侧炮座，也用于圣血天使战团的巴尔掠食者。'},notes={2:'several Space Marine vehicles指多种载具配用的重型火焰喷射器，不是将几辆载具的总火力拿来比较。'},terms=[('Flamestorm Cannon','火焰风暴炮')])
save(1275,{2:'焚化枪由机械修会技术工匠在火卫二上独家制造，专为灰骑士设计。',4:'Grey Knight with Incinerator 装备焚化枪的灰骑士',7:'它与帝国其他部队使用的重型火焰喷射器有许多相似之处，但燃料是“灵能火”——一种由注入灵能的祝圣钷素和圣油调制的特殊混合物，可以绕过灵能力量或巫术提供的防护。这种火焰以纯粹信仰燃烧，呈现湛蓝与耀白色，比普通火焰更热，对恶魔尤其有效。若持枪者本人也是灵能者，还可注入自身力量，增强并引导喷流，进一步提升效果。',9:'Grey Knights Terminator with Incinerator 装备焚化枪的灰骑士终结者',11:'见识到盟友武器的可怕威力后，恶魔审判庭的审判官开始寻求适合普通人使用的轻型焚化枪。这种尺寸接近常规火焰喷射器的型号，会配发给审判庭焚火者，国教会也有使用。大多数存放于圣地修道院的军械库中，只有极少数交给最狂热的传教士，帮助他们清洗拒绝帝国信条的人。',12:'Heavy Incinerator 重型焚化枪',14:'重型焚化枪比灰骑士的常规焚化枪大得多，威力也强得多，目前仅见于涅墨西斯骇骑机甲。',16:'Heavy Incinerator 重型焚化枪'},notes={2:'Deimos本身就是火卫二，原译“火卫二的卫星”多出了一层天体从属关系。',11:'Inquisitorial Pyroclasts为审判庭人员，按105篇焚火者；不同于火蜥蜴同名兵种。'},terms=[('Incinerator','焚化枪'),('Psyflame','灵能火'),('Heavy Incinerator','重型焚化枪'),('Inquisitorial Pyroclasts','审判庭焚火者')],title='焚化枪 Incinerator')
save(1276,{2:'热熔武器威力强大，主要有两类原理：一是扰动目标的亚原子结构，将其烤灼或熔化；另一类则制造小规模聚变反应，把释放的能量投射为热能冲击，几乎能烧穿任何物质。部分帝国型号使用派鲁姆与钷素混合燃料。目标距离越近，效果越强。',6:'虽然射程短、射速低，热熔武器仍因出色的反装甲能力而备受重视。它也被视为等离子武器的理想替代品，后者性能不稳定，甚至可能杀死使用者。除了目标体内水分剧烈汽化时的轰响，热熔武器本身开火声很小。渗透部队因而常借助它安静而高效的特点，在敌方载具来得及投入战斗前就将其摧毁。',8:'许多种族都使用这种基本技术。帝国通常称其为热熔武器，也有“聚变枪”“熔化器”“烤炉”和“汽化枪”等俗称。其他种族的同类武器效果相近，技术与运作方式有时却截然不同。钛族和灵族也像帝国一样，主要将热熔武器用于反坦克作战。',12:'热熔枪是帝国最常见的热熔武器，广泛装备于帝国卫队、星际战士、异端审判庭及修女会等武装力量。',18:'多管热熔是更重型的版本，主要安装于载具，有时也由星际战士破坏者小队和战斗修女携带。',21:'地狱火手枪是一种十分罕见的小型热熔武器，仅由战斗修女、异端审判庭和恶魔审判庭的特工，以及少数星际战士使用，例如圣血天使指挥官但丁和先锋老兵。',24:'热熔炮是一种能同时摧毁多个目标的大型车载热熔武器，可见于地狱犬的恶魔犬改型。若干帝国泰坦型号还装备尺寸更大的热熔炮。',31:'巨型热熔是一种古老武器，最初用于太空作战，后来也装备于火卫二型炼狱掠食者等载具。',38:'热熔鱼雷是帝国海军军舰使用的强大燃烧武器。',54:'热线光矛融合了热熔和激光技术，主要由黑暗灵族劫掠者与天灾使用。',56:'Fusion Blaster 融合爆破炮',58:'融合爆破炮是钛族使用的武器，威力与帝国对应型号相近。',61:'融合速射枪是新开发的钛族武器，能够点射连发。由于单轮射击弹量增加，每发威力低于帝国同类武器，装备于新式战斗服。',64:'融合对撞枪是一种安装在战斗服上的重型反坦克武器。',67:'融合根除者是钛族融合武器中规模最大、威力最强的一类。',68:'Necron Melta Weapons 太空死灵热熔武器',71:'热线炮是太空死灵通常安装在哨兵炮塔上的武器。',74:'热射线是三圣追猎者装备的太空死灵武器，具有反坦克和反步兵两种射击模式。'},notes={2:'原译遗漏Pyrum燃料组分，暂译派鲁姆并保留原拼写登记；不补充现实燃料配方。',8:'vape在此指汽化，不能译成电子烟；cookers为武器绰号，非实用炊具。',64:'heavy修饰武器，原译将其错接为重型战斗服。'},terms=[('Melta Weapon','热熔武器'),('Pyrum','派鲁姆'),('Meltagun','热熔枪'),('Melta Rifle','热熔步枪'),('Multi-melta','多管热熔'),('Inferno Pistol','地狱火手枪'),('Melta Cannon','热熔炮'),('Melta Lance','热熔长枪'),('Melta Destroyer','热熔毁灭炮'),('Melta Blast-Gun','热熔爆破枪'),('Siege Melta Array','攻城热熔阵列'),('Magna-Melta','巨型热熔'),('Cyclonic Melta Lance','旋风热熔光矛'),('Thermal Spear','热能矛'),('Melta Torpedo','热熔鱼雷'),('Fire Pike','火矛'),('Fusion Gun','聚变枪'),('Fusion Pistol','聚变手枪'),('Inferno Lance','炼狱光矛'),('Heat Lance','热线光矛'),('Fusion Blaster','融合爆破炮'),('Fusion Cascade','融合速射枪'),('Fusion Collider','融合对撞枪'),('Fusion Eradicator','融合根除者'),('Heat Cannon','热线炮'),('Heat Ray','热射线'),('Triarch Stalker','三圣追猎者')])
save(1277,{2:'热熔枪是热熔武器的基础版本，由帝国出身的各支部队使用，包括帝国卫队、星际战士、异端审判庭和修女会。它安静而高效，渗透部队常用它在敌方载具投入战斗前将其摧毁。“聚变枪”“熔化器”和“烤炉”也是它的俗称。',4:'Cadian Shock Trooper 卡迪亚突击军士兵',6:'Catachan Jungle Fighter 卡塔昌丛林斗士',9:'热熔枪是有效的反装甲武器，帝国各部队将其用于近距离突击和反坦克任务。它在近距离时威力最强，能以超高温冲击把几乎任何材料化为熔渣。',13:'已知或有记载的热熔枪产地与型号',19:'阿卡特兰型 Mk.VIII——艾丽西亚空降部队使用。',21:'Accataran Pattern MkVIII Meltagun 阿卡特兰型 Mk.VIII 热熔枪',32:'热熔卡宾枪——由风暴天鹰使用。',34:'Tempestus Aquilon with Melta Carbine 装备热熔卡宾枪的风暴天鹰'},notes={19:'原译把Mk.VIII的8型抄成Mk.VII的7型，已按英文修正；Accataran与已定Accatran按同产地统一中文，英文原样保留。',32:'GW09/GW10第8页Tempestus Aquilons官方对应为风暴天鹰。'},terms=[('Melta Gun','热熔枪'),('Accataran Pattern MkVIII Meltagun','阿卡特兰型 Mk.VIII 热熔枪'),('Melta Carbine','热熔卡宾枪'),('Tempestus Aquilons','风暴天鹰')])
save(1278,{2:'热熔步枪是原铸根除者小队使用的热熔武器。此外还有尺寸更大的重型热熔步枪，以电缆直接连接使用者的动力装甲供能。'},terms=[('Melta Rifle','热熔步枪'),('Heavy Melta Rifle','重型热熔步枪')])
import json,csv
from pathlib import Path
p=Path(__file__).parent;f=p/'edits.json';d=json.loads(f.read_text());d={k:v.replace('重型焚化炮','重型焚化枪') for k,v in d.items()};f.write_text(json.dumps(d,ensure_ascii=False,indent=2))
f=p/'terms.tsv';r=list(csv.DictReader(f.open(),delimiter='\t'))
for x in r:
 if x['英文标准词'] in ['Triarch Stalker','Tempestus Aquilons']:
  x['译名状态']='官方已核对';x['依据']='https://assets.warhammer-community.com/chi_06-05_wh40k_core%26key_munitorum_field_manual-5mrlucr2t1-fkybzzzoce.pdf ; https://assets.warhammer-community.com/eng_warhammer40000_munitorum_field_manual_march_2025-cims9ya3sg-s8j9m2haae.pdf';x['定位']='GW09/GW10第28页' if x['英文标准词']=='Triarch Stalker' else 'GW09/GW10第8页';x['编辑说明']='官方双语同名单位逐项对照。'
with f.open('w',newline='') as o:w=csv.DictWriter(o,fieldnames=list(r[0]),delimiter='\t');w.writeheader();w.writerows(r)
